### ISSUE TITLE
Complete WebAssembly Foreign WNFS Blockstore Implementation

### ISSUE THREAD

**Issue by expede** [WebNativeFileSystem/rs-wnfs#15]

**Comment by appcypher** [comment]
## Description

Right now we have a memory-based block store that works well for testing purposes but to make the js bindgen useful, we need the generated wasm code to be able to use some imported foreign block store.

The idea is to expose foreign function interfaces that will allow the wasm side to call and use some opaque block store object passed in from JavaScript code. It has to be implemented in a way that won't result in adding wasm or js specific details to the rust core.

https://github.com/WebNativeFileSystem/rs-wnfs/blob/8e59f1f056ed3b526ce1f63e789de53fa94c11b3/crates/wasm/fs/blockstore.rs#L19-L31

**Comment by appcypher** [comment]
Fixed by https://github.com/WebNativeFileSystem/rs-wnfs/pull/13
