### ISSUE TITLE
More precise typescript types

### ISSUE THREAD

**Issue by matheus23** [WebNativeFileSystem/rs-wnfs#32]
# Summary

The typescript types generated from wasm-bindgen aren't very precise, see for example:

```ts
/**
* Returns the name and metadata of the direct children of a directory.
* @param {Array<any>} path_segments
* @param {any} store
* @returns {Promise<any>}
*/
  ls(path_segments: Array<any>, store: any): Promise<any>;
```

I think `path_segments` could be `Array<string>`, and `store: ForeignBlockStore`?

## Problem

This helps orient users using TS types for autocompletion in IDEs, for example. Also makes sure that there are fewer accidental runtime errors.

### Impact

Not big, only people using the `wnfs` npm package. Which is mostly me at the moment. I think it's fair to expect anyone else to use webnative, not `wnfs` directly.

## Solution

I don't know. Maybe a setting in wasm-bindgen? Something that needs to be configured? Is that perhaps an issue with wasm-bindgen and they need to fix it?

**Comment by appcypher** [comment]
Found a solution to this.

https://github.com/rustwasm/wasm-bindgen/issues/1197#issuecomment-596228593

We could have a `types.rs` file for the type annotations

```rs
#[wasm_bindgen(typescript_custom_section)]
const TS_BLOCKSTORE: &'static str = r#"
export interface BlockStore {
    putBlock(bytes: string): Promise<Uint8Array>;
    getBlock(cid: Uint8Array): Promise<Uint8Array>;
}
"#;
```

```rs
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "BlockStore")]
    pub type BlockStore;

    // ...
}
```
